#!/bin/bash

if [ ! $1 ]; then
  echo " Usage: $0 <database_name> <target_directory>"
  exit 1
fi
db=$1
target_directory=$2
if [ ! $target_directory ]; then
  target_directory="./"
else
  mkdir -p $target_directory
fi

tmp_file="jaldAIyni8FmETkUvmk46S89.js"
echo "print('_ ' + db.getCollectionNames())" > $tmp_file
cols=`mongo $db $tmp_file | grep '_' | awk '{print $2}' | tr ',' ' '`
for c in $cols
do
  mongoexport -d $db -c $c -o "$target_directory/exp_${db}_${c}.json"
done
rm $tmp_file