#!/bin/bash

if [ ! $1 ]; then
  echo " Usage: $0 <database_name> <target_directory>"
  exit 1
fi
db=$1
out_dir=$2
if [ ! $out_dir ]; then
  out_dir="./"
else
  mkdir -p $out_dir
fi

tmp_file="jaldAIyni8FmETkUvmk46S89.js"
echo "print('_ ' + db.getCollectionNames())" > $tmp_file
cols=`mongo $db $tmp_file | grep '_' | awk '{print $2}' | tr ',' ' '`
for c in $cols
do
  mongoexport -d $db -c $c -o "$out_dir/exp_${db}_${c}.json"
done
rm $tmp_file